name: lXt

channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - biotite >= 0.35.0
  - mafft >= 7.508
  - more-itertools >= 9.0
  - networkx >= 2.8.6
  - numpy >= 1.23
  - toolz >= 0.12
  - typing_extensions >= 4.3.0
  - tqdm >= 4.64
  - pandas >= 1.5
  - pyhmmer >= 0.6.3
  - python >= 3.10
  - requests >= 2.28