name: lXt-dev

channels:
  - conda-forge
  - bioconda
  - anaconda

dependencies:
  - biotite >= 0.35.0
  - fastpdb >= 1.0
  - joblib >= 1.1
  - mafft >= 7.508
  - more-itertools >= 9.0
  - networkx >= 2.8.6
  - numpy >= 1.23
  - tqdm >= 4.64
  - pandas >= 1.5
  - pyhmmer >= 0.6.3
  - pytest >= 7.1.2
  - requests >= 2.28
  - sphinx 5.1.1
  - sphinx-material >= 0.0.35
