name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

  jobs:
    build and publish:
      runs-on: ${{ matrix.os }}-latest
      strategy:
        fail-fast: false
        matrix:
          os: [ "ubuntu", "macos" ]
          python-version: [ "3.10", "3.11" ]
      defaults:
        run:
          shell: bash -l {0}
      steps:
        - uses: actions/checkout@v3

        - shell: bash
          run: |
            hatch build

        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
