name: Publish

env:
  ARTIFACT: artifact.bin

on:
  workflow_dispatch:
  release:
    types: [published]

  jobs:
    build:
      runs-on: ${{ matrix.os }}-latest
      strategy:
        fail-fast: false
        matrix:
          os: [ "ubuntu", "macos" ]
          python-version: [ "3.10", "3.11" ]
      defaults:
        run:
          shell: bash -l {0}
      steps:
        - uses: actions/checkout@v3

        - shell: bash
          run: |
            hatch build

        - uses: actions/upload-artifact@v2
          with:
            name: build-${{ matrix.os }}-${{ github.sha }}
            path: ${{ env.ARTIFACT }}

    publish:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/download-artifact@v2
          with:
            path: artifacts

        - shell: bash
          working-directory: artifacts
          run: |
            for i in $( ls ); do
              cat $i/$ARTIFACT
            done
