name: Auto-testing with miniconda

on: [push]

jobs:
  test:
    name:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]

    steps:
      - name: Set up environment
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          mamba-version: '*'
          channels: conda-forge, defaults, bioconda
          channels-priority: true
          activate-environment: lXt-dev
          environment-file: environment.yml
      - name: Test with pytest
        run: |
          pytest
